// GENERATED by tool/seed_vectors_oracle.py. Do not edit by hand.
//
// Regenerate with:  python3 tool/seed_vectors_oracle.py
//
// THIS TABLE WAS NOT PRODUCED BY THE CODE IT TESTS. The oracle is an
// independent Python implementation of FNV-1a-64 and SplitMix64,
// written from their published definitions, so it can disagree with
// lib/core/seeded_generator.dart. A table generated by the
// implementation would freeze that implementation's bugs as the
// specification.
//
// CI verifies these values; it never regenerates them.
//
// Exact 64-bit values on the native target this app ships to.
// ignore_for_file: avoid_js_rounded_ints, unnecessary_library_directive
library;

/// One frozen row: a key, its hash, its seed and the draws it yields.
typedef SeedVector = ({
  String key,
  String why,
  int hash,
  int seed,
  List<int> draws,
});

/// The salt the vectors were computed with. Frozen forever.
const int kVectorFeatureSalt = 0x5354524F4F50;

/// The mode salt the vectors were computed with. Frozen forever.
const int kVectorModeSalt = 0x424C495A;

/// How many draws each row freezes, and their bound.
const int kVectorDrawCount = 16;

/// The exclusive upper bound of every frozen draw.
const int kVectorDrawBound = 1000;

/// The frozen vectors.
const List<SeedVector> kSeedVectors = <SeedVector>[
  (
    key: 'stroop_rush',
    why: 'the first shipped game',
    hash: 0x10897B5A5AE009DD,
    seed: 0x651C8A84D0A00117,
    draws: <int>[
      374,
      739,
      258,
      650,
      12,
      820,
      764,
      150,
      336,
      307,
      267,
      167,
      466,
      217,
      182,
      86,
    ],
  ),
  (
    key: 'schulte_grid',
    why: 'the second, which proves the seam',
    hash: 0x67627869782C8AC,
    seed: 0x73E3D6581DC2C066,
    draws: <int>[
      648,
      215,
      342,
      325,
      860,
      688,
      170,
      356,
      802,
      605,
      492,
      146,
      633,
      286,
      368,
      466,
    ],
  ),
  (
    key: '',
    why: 'the empty key, which must still hash',
    hash: -0x340D631B7BDDDCDB,
    seed: -0x419892C5F19DD411,
    draws: <int>[
      199,
      648,
      984,
      660,
      744,
      257,
      200,
      270,
      221,
      446,
      51,
      20,
      46,
      41,
      902,
      924,
    ],
  ),
  (
    key: '2026-01-01T00:00:00.000Z',
    why: 'a real run key: an ASCII ISO-8601 instant from the injected clock',
    hash: -0x136BD873C2B79FB5,
    seed: -0x66FE29AD48F7977F,
    draws: <int>[
      558,
      580,
      24,
      74,
      500,
      731,
      537,
      508,
      926,
      76,
      828,
      7,
      798,
      456,
      387,
      423,
    ],
  ),
  (
    key: 'run-\u{6f1}\u{6f2}\u{6f3}',
    why:
        'Persian digits U+06Fx. PINS THE BYTE PATH, and does not sanction a non-ASCII key: seedFrom asserts against exactly this',
    hash: -0x1F9EE57CC563FC06,
    seed: -0x6A0B14A24F23F4D0,
    draws: <int>[
      199,
      731,
      940,
      441,
      54,
      228,
      139,
      852,
      157,
      991,
      884,
      582,
      238,
      876,
      671,
      923,
    ],
  ),
  (
    key: '\u{695}\u{6d5}\u{646}\u{6af}',
    why:
        'Sorani, including U+0695. Two-byte and three-byte UTF-8 sequences, so a code-unit hash disagrees here and nowhere else',
    hash: -0x34E1F6074105D3A4,
    seed: -0x417407D9CB45DB6A,
    draws: <int>[
      773,
      434,
      858,
      142,
      740,
      846,
      640,
      557,
      90,
      948,
      345,
      740,
      469,
      470,
      384,
      852,
    ],
  ),
];
