#!/usr/bin/env python3
"""Write the reference manifest beside a captured screen set.

  usage: write-manifest.py <dest-dir> <app.html> <strings-fa.json> <0|1 rtl>

Every hash here is recomputed by `test/policy/reference_manifest_test.dart`, so
a source edited without a re-capture, or a PNG replaced by hand, fails CI. That
is not hypothetical: `app.html` once carried `data-num="640"` while the
committed `06-results.png` still showed a Latin `640`, and every gate was green.
"""

import hashlib
import json
import os
import sys


def digest(path: str) -> str:
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def main() -> int:
    dest, src, strings, rtl = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4] == "1"

    sources = {"app.html": digest(src)}
    if rtl:
        # The RTL set is rendered THROUGH the dump, so a re-dump without a
        # re-capture is the same class of drift.
        sources["rtl/strings-fa.json"] = digest(strings)

    manifest = {
        "_note": (
            "GENERATED by capture-screens.sh. Do not hand-edit: "
            "test/policy/reference_manifest_test.dart recomputes every hash."
        ),
        "sources": sources,
        "screens": {
            name[:-4]: digest(os.path.join(dest, name))
            for name in sorted(os.listdir(dest))
            if name.endswith(".png")
        },
    }

    with open(os.path.join(dest, "manifest.json"), "w", encoding="utf-8") as out:
        out.write(json.dumps(manifest, indent=2) + "\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
