// GENERATED by tool/update_schulte_vectors.dart. Do not edit by hand.
//
// See the header on kSchulteScrambleVectors for what these rows do and do
// not prove.
//
// A fingerprint is an exact 64-bit integer on a native target
// and silently wrong on the web. The app ships iOS only, and
// the lint is suppressed here rather than repository-wide so
// it still fires anywhere else someone writes one — the same
// decision lib/core/seeded_generator.dart records.
// ignore_for_file: avoid_js_rounded_ints
import 'package:mindforge/core/seeded_generator.dart';

/// One frozen board.
typedef SchulteScrambleVector = ({
  int seed,
  int size,
  int fingerprint,
  int firstCell,
  int naturalPositions,
  String note,
});

/// The fingerprint of [cells].
///
/// `join(',')` goes through `int.toString()`, which is ASCII by
/// definition and reads no ambient locale — so a fingerprint is
/// locale-invariant BY CONSTRUCTION, not by luck. That is the
/// line a well-meaning move to a NumberFormat would change, and
/// schulte_scramble_locale_test is what would catch it.
int fingerprintOf(List<int> cells) => fnv1a64(cells.join(','));

/// Boards frozen against accidental change.
///
/// **Only the four size-3 rows are independently derived.** The
/// rest are regression pins: they prove nothing changed, never
/// that the output is right. What argues for correctness is the
/// BigInt oracle in schulte_oracle.dart, which reimplements
/// SplitMix64 and the shuffle from their definitions and agrees
/// with production over 500 seeds at three sizes.
const List<SchulteScrambleVector> kSchulteScrambleVectors =
    <SchulteScrambleVector>[
      (
        seed: 0,
        size: 3,
        fingerprint: 7122428147940110308,
        firstCell: 6,
        naturalPositions: 0,
        note: 'hand-computed anchor',
      ),
      (
        seed: 1,
        size: 3,
        fingerprint: -4868790583433053236,
        firstCell: 8,
        naturalPositions: 1,
        note: 'hand-computed anchor',
      ),
      (
        seed: 2,
        size: 3,
        fingerprint: -8399518840264783012,
        firstCell: 7,
        naturalPositions: 0,
        note: 'hand-computed anchor',
      ),
      (
        seed: 3,
        size: 3,
        fingerprint: 1480211273524249252,
        firstCell: 8,
        naturalPositions: 0,
        note: 'hand-computed anchor',
      ),
      (
        seed: 0,
        size: 4,
        fingerprint: -446377520532009298,
        firstCell: 3,
        naturalPositions: 0,
        note: 'chill, the low seed',
      ),
      (
        seed: 1,
        size: 4,
        fingerprint: -8525560971307553412,
        firstCell: 9,
        naturalPositions: 0,
        note: 'chill, the next seed',
      ),
      (
        seed: 0,
        size: 5,
        fingerprint: -5685758299987598630,
        firstCell: 14,
        naturalPositions: 0,
        note: 'classic, the low seed',
      ),
      (
        seed: 1,
        size: 5,
        fingerprint: -199750299756316472,
        firstCell: 15,
        naturalPositions: 1,
        note: 'classic, the next seed',
      ),
      (
        seed: 2,
        size: 5,
        fingerprint: -6144671551072552838,
        firstCell: 18,
        naturalPositions: 0,
        note: 'classic',
      ),
      (
        seed: 42,
        size: 5,
        fingerprint: -2551250823933753420,
        firstCell: 25,
        naturalPositions: 1,
        note: 'classic, the seed every test uses',
      ),
      (
        seed: 999999,
        size: 5,
        fingerprint: -142226832530954908,
        firstCell: 7,
        naturalPositions: 2,
        note: 'classic, a large seed',
      ),
      (
        seed: 9223372036854775807,
        size: 5,
        fingerprint: -5445817762187298732,
        firstCell: 18,
        naturalPositions: 1,
        note: 'classic, the largest positive seed',
      ),
    ];
