@Tags(['tool'])
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mindforge/core/supported_locale.dart';
import 'package:mindforge/l10n/app_localizations.dart';
import 'package:mindforge/l10n/locale_numbers.dart';

import '../test/support/l10n_strings.dart';

/// Writes `design/sunburst-pop/rtl/strings-fa.json` from the **live** Persian
/// localisations.
///
/// It is a test rather than a script because the generated localisations import
/// `package:flutter/widgets.dart` and only `flutter test` can load them. It is
/// tagged `tool` and excluded from the default lane, because it WRITES — and a
/// gate that regenerates what it checks asserts nothing.
///
/// CI runs it and then diffs the output. Editing an ARB without re-dumping is
/// therefore a build failure, which is what keeps the reference screenshots and
/// the app **one** source rather than two that drift.
///
///   flutter test --tags tool tool/dump_design_strings_test.dart
void main() {
  test('dump the fa strings the RTL reference screens render', () async {
    final fa = await AppLocalizations.delegate.load(const Locale('fa'));

    // Numbers arrive PRE-FORMATTED. gen-l10n interpolates an int placeholder
    // with Dart toString(), which is Latin digits in every locale — measured,
    // streakDays rendered "4" instead of "۴" before this changed.
    String n(int value) => const LocaleNumbers(SupportedLocale.fa).count(value);

    // Every message the eight screens use, rendered through the ONE table
    // test/l10n/text_expansion_matrix_test.dart also lays out. A second copy
    // here would let a key be measured in one place and rendered in the other.
    final strings = renderAllStrings(fa, SupportedLocale.fa);

    // The literal values on the reference screens, each formatted through
    // LocaleNumbers exactly as the app would. A Latin digit surviving into an
    // RTL screenshot means one of these was missed.
    // One formatter, bound once: LocaleNumbers is locale-bound so the
    // locale cannot be threaded wrong on one line out of forty.
    const fmt = LocaleNumbers(SupportedLocale.fa);
    final numbers = <String, String>{
      // Every distinct data-num value in app.html's eight figures. The Schulte
      // TILES are in here because the tiles ARE the numbers: a Latin digit on
      // that board is not a cosmetic slip, it is the game rendered in the
      // wrong script. test/policy/rtl_screens_test.dart asserts this map
      // covers every data-num node, so a new one cannot be missed.
      '1': n(1),
      '2': n(2),
      '3': n(3),
      '4': n(4),
      '5': n(5),
      '6': n(6),
      '7': n(7),
      '8': n(8),
      '9': n(9),
      '10': n(10),
      '11': n(11),
      '12': n(12),
      '13': n(13),
      '14': n(14),
      '15': n(15),
      '16': n(16),
      '17': n(17),
      '18': n(18),
      '19': n(19),
      '20': n(20),
      '21': n(21),
      '22': n(22),
      '23': n(23),
      '24': n(24),
      '25': n(25),
      '128': n(128),
      '640': n(640),
      '780': n(780),
      '860': n(860),
      '940': n(940),
      '1120': n(1120),
      '1180': n(1180),
      '1310': n(1310),
      '1480': n(1480),
      '1,480': n(1480),
      '1,240': n(1240),
      '18.6s': '${fmt.seconds(18600)}${fa.unitSeconds}',
      '0:23': fmt.clock(23000),
      '0:12.4':
          '${fmt.clock(12000)}'
          '${fmt.seconds(400).substring(1)}',
      '92%': fmt.percent(0.92),
    };

    final file = File('design/sunburst-pop/rtl/strings-fa.json')
      ..writeAsStringSync(
        '${const JsonEncoder.withIndent('  ').convert(<String, Object>{
          '_note': 'GENERATED by tool/dump_design_strings_test.dart from '
              'lib/l10n/app_fa.arb and lib/l10n/locale_numbers.dart. Do not '
              'hand-edit: CI regenerates it and diffs the result, so an ARB '
              'change without a re-dump fails the build.',
          'strings': strings,
          'numbers': numbers,
        })}\n',
      );

    expect(file.existsSync(), isTrue);
  });
}
