@Tags(['tool'])
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mindforge/core/supported_locale.dart';
import 'package:mindforge/l10n/app_localizations.dart';
import 'package:mindforge/l10n/locale_numbers.dart';

import '../test/support/l10n_strings.dart';

/// Writes `design/sunburst-pop/rtl/strings-fa.json` from the **live** Persian
/// localisations.
///
/// It is a test rather than a script because the generated localisations import
/// `package:flutter/widgets.dart` and only `flutter test` can load them. It is
/// tagged `tool` and excluded from the default lane, because it WRITES — and a
/// gate that regenerates what it checks asserts nothing.
///
/// CI runs it and then diffs the output. Editing an ARB without re-dumping is
/// therefore a build failure, which is what keeps the reference screenshots and
/// the app **one** source rather than two that drift.
///
///   flutter test --tags tool tool/dump_design_strings_test.dart
void main() {
  test('dump the fa strings the RTL reference screens render', () async {
    final fa = await AppLocalizations.delegate.load(const Locale('fa'));

    // Every message the eight screens use, rendered through the ONE table
    // test/l10n/text_expansion_matrix_test.dart also lays out. A second copy
    // here would let a key be measured in one place and rendered in the other.
    // One formatter, bound once: LocaleNumbers is locale-bound, so the locale
    // cannot be threaded wrong on one line out of forty.
    //
    // Numbers arrive PRE-FORMATTED. gen-l10n interpolates an int placeholder
    // with Dart toString(), which is Latin digits in every locale — measured,
    // streakDays rendered "4" instead of "۴" before this changed.
    const fmt = LocaleNumbers(SupportedLocale.fa);

    final strings = <String, String>{
      ...renderAllStrings(fa),
      // A message the design renders TWICE with different arguments: the HUD
      // shows the live streak and the results card the longest one. The dump
      // is key -> one string, so the second reading is a variant, keyed
      // "message/variant" and marked with data-l10n-variant in app.html.
      //
      // It lives here rather than in renderAllStrings because that table is
      // asserted key-for-key against the template ARB, and a variant is not an
      // ARB message.
      'streakMultiplier/11': fa.streakMultiplier(11, fmt.count(11)),
    };

    // The literal values on the reference screens, each formatted through
    // LocaleNumbers exactly as the app would. A Latin digit surviving into an
    // RTL screenshot means one of these was missed.
    // One formatter, bound once: LocaleNumbers is locale-bound so the
    // locale cannot be threaded wrong on one line out of forty.
    // Every distinct data-num value in app.html's eight figures. The Schulte
    // TILES are the 1..25 run: they are in here because on that board the tiles
    // ARE the numbers, so a Latin digit there is not a cosmetic slip, it is the
    // game rendered in the wrong script.
    //
    // The plain integers are generated rather than typed out, because
    // thirty-four `'N': n(N)` rows are thirty-four chances to typo one and a
    // reader cannot see which. test/policy/rtl_screens_test.dart asserts this
    // map covers every data-num node, so a value the design adds later cannot
    // be missed silently.
    final numbers = <String, String>{
      for (final value in <int>[
        ...List<int>.generate(25, (i) => i + 1),
        128,
        640,
        780,
        860,
        940,
        1120,
        1180,
        1310,
        1480,
      ])
        '$value': fmt.count(value),
      // The four whose design text is not just the integer.
      '1,480': fmt.count(1480),
      '1,240': fmt.count(1240),
      '18.6s': '${fmt.seconds(18600)}${fa.unitSeconds}',
      '0:23': fmt.clock(23000),
      '0:12.4': '${fmt.clock(12000)}${fmt.seconds(400).substring(1)}',
      '92%': fmt.percent(0.92),
    };

    final file = File('design/sunburst-pop/rtl/strings-fa.json')
      ..writeAsStringSync(
        '${const JsonEncoder.withIndent('  ').convert(<String, Object>{
          '_note': 'GENERATED by tool/dump_design_strings_test.dart from '
              'lib/l10n/app_fa.arb and lib/l10n/locale_numbers.dart. Do not '
              'hand-edit: CI regenerates it and diffs the result, so an ARB '
              'change without a re-dump fails the build.',
          'strings': strings,
          'numbers': numbers,
        })}\n',
      );

    expect(file.existsSync(), isTrue);
  });
}
