#!/usr/bin/env python3
"""Writes test/core/seed_vectors.dart from an INDEPENDENT implementation.

The point of this file is that it is not the code under test. FNV-1a-64 and
SplitMix64 are reimplemented here from their published definitions, in a
different language, so a vector table generated from it can disagree with
lib/core/seeded_generator.dart. A table generated by the implementation would
freeze whatever that implementation happened to do, including its bugs.

Run:  python3 tool/seed_vectors_oracle.py
CI verifies the committed table matches; it never regenerates it.
"""

MASK64 = (1 << 64) - 1

FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3


def fnv1a64(key: str) -> int:
    """FNV-1a over the UTF-8 BYTES of key, not its code units."""
    h = FNV_OFFSET
    for byte in key.encode("utf-8"):
        h = ((h ^ byte) * FNV_PRIME) & MASK64
    return h


GOLDEN_GAMMA = 0x9E3779B97F4A7C15


def splitmix64(state: int):
    """One SplitMix64 step: returns (next_state, output)."""
    state = (state + GOLDEN_GAMMA) & MASK64
    z = state
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
    return state, z ^ (z >> 31)


def seed_from(key: str, feature_salt: int, mode_salt: int = 0) -> int:
    """The app-facing seed: the key's hash mixed with two frozen salts."""
    return (fnv1a64(key) ^ (feature_salt * GOLDEN_GAMMA) ^ mode_salt) & MASK64


def draws(seed: int, count: int, bound: int):
    """`count` values of nextInt(bound).

    The modulo is taken on the SIGNED value, because that is what Dart can
    express: Dart's int is signed 64-bit and has no unsigned 64-bit type, and
    both languages' `%` return a non-negative result for a positive divisor. An
    unsigned modulo here would be a definition the implementation could not
    match, which is how the first draft of these two disagreed.
    """
    state = seed
    out = []
    for _ in range(count):
        state, value = splitmix64(state)
        out.append(to_signed(value) % bound)
    return out


def to_signed(value: int) -> int:
    """Dart ints are signed 64-bit; Python's are unbounded."""
    return value - (1 << 64) if value >= (1 << 63) else value


# The keys. Each row says why it is here.
KEYS = [
    ("stroop_rush", "the first shipped game"),
    ("schulte_grid", "the second, which proves the seam"),
    ("", "the empty key, which must still hash"),
    (
        "2026-01-01T00:00:00.000Z",
        "a real run key: an ASCII ISO-8601 instant from the injected clock",
    ),
    (
        "run-۱۲۳",
        "Persian digits U+06Fx. PINS THE BYTE PATH, and does not sanction a "
        "non-ASCII key: seedFrom asserts against exactly this",
    ),
    (
        "ڕەنگ",
        "Sorani, including U+0695. Two-byte and three-byte UTF-8 sequences, "
        "so a code-unit hash disagrees here and nowhere else",
    ),
]

FEATURE_SALT = 0x5354524F4F50  # 'STROOP'
MODE_SALT = 0x424C495A  # 'BLIZ'


def dart_literal(value: int) -> str:
    signed = to_signed(value)
    return f"-0x{-signed:X}" if signed < 0 else f"0x{signed:X}"


def main() -> None:
    lines = [
        "// GENERATED by tool/seed_vectors_oracle.py. Do not edit by hand.",
        "//",
        "// Regenerate with:  python3 tool/seed_vectors_oracle.py",
        "//",
        "// THIS TABLE WAS NOT PRODUCED BY THE CODE IT TESTS. The oracle is an",
        "// independent Python implementation of FNV-1a-64 and SplitMix64,",
        "// written from their published definitions, so it can disagree with",
        "// lib/core/seeded_generator.dart. A table generated by the",
        "// implementation would freeze that implementation's bugs as the",
        "// specification.",
        "//",
        "// CI verifies these values; it never regenerates them.",
        "//",
        "// Exact 64-bit values on the native target this app ships to.",
        "// ignore_for_file: avoid_js_rounded_ints, unnecessary_library_directive",
        "library;",
        "",
        "/// One frozen row: a key, its hash, its seed and the draws it yields.",
        "typedef SeedVector = ({",
        "  String key,",
        "  String why,",
        "  int hash,",
        "  int seed,",
        "  List<int> draws,",
        "});",
        "",
        "/// The salt the vectors were computed with. Frozen forever.",
        f"const int kVectorFeatureSalt = {dart_literal(FEATURE_SALT)};",
        "",
        "/// The mode salt the vectors were computed with. Frozen forever.",
        f"const int kVectorModeSalt = {dart_literal(MODE_SALT)};",
        "",
        "/// How many draws each row freezes, and their bound.",
        "const int kVectorDrawCount = 16;",
        "",
        "/// The exclusive upper bound of every frozen draw.",
        "const int kVectorDrawBound = 1000;",
        "",
        "/// The frozen vectors.",
        "const List<SeedVector> kSeedVectors = <SeedVector>[",
    ]

    for key, why in KEYS:
        h = fnv1a64(key)
        seed = seed_from(key, FEATURE_SALT, MODE_SALT)
        row_draws = draws(seed, 16, 1000)
        escaped = key.replace("\\", "\\\\").replace("'", "\\'")
        escaped = "".join(
            c if ord(c) < 0x80 else f"\\u{{{ord(c):x}}}" for c in escaped
        )
        lines += [
            "  (",
            f"    key: '{escaped}',",
            f"    why: '{why}',",
            f"    hash: {dart_literal(h)},",
            f"    seed: {dart_literal(seed)},",
            f"    draws: <int>[{', '.join(str(d) for d in row_draws)}],",
            "  ),",
        ]

    lines += ["];", ""]

    with open("test/core/seed_vectors.dart", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote test/core/seed_vectors.dart with {len(KEYS)} rows")


if __name__ == "__main__":
    main()
