#!/usr/bin/env python3
"""Writes test/games/stroop_rush/domain/stroop_vectors.dart from an INDEPENDENT
implementation of Stroop Rush's round generator.

THE POINT OF THIS FILE IS THAT IT IS NOT THE CODE UNDER TEST. The PRNG, the
seed derivation, the shuffle and the four-draw order are reimplemented here from
the specification in the generator's own doc comment, in a different language,
so a table generated from it can DISAGREE with
lib/games/stroop_rush/domain/stroop_round_generator.dart. A table generated by
the implementation would freeze that implementation's bugs as the specification.

E09 T09.2 asks for a Dart oracle under test/.../oracle/. This is Python instead,
for two reasons: E07 already established the convention with
tool/seed_vectors_oracle.py, and a second Dart transcription living in the same
package can import — by hand or by an IDE's auto-import — the very file it
exists to disagree with. A different language cannot.

It is also LOCALE-FREE by construction: Python's int formatting has no locale,
so a fingerprint computed here cannot pick one up. That is half the proof that
the Dart side has not either.

Run:  python3 tool/stroop_vectors_oracle.py
CI verifies the committed table matches; it never regenerates it.
"""

MASK64 = (1 << 64) - 1
SIGN_BIT = 1 << 63

FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3
GOLDEN_GAMMA = 0x9E3779B97F4A7C15

# lib/games/stroop_rush/domain/stroop_round_generator.dart
STROOP_FEATURE_SALT = 0x5354524F4F50

# PlayAnswer, in declaration order. The INDEX is the contract; the name is here
# only so a human reading a regenerated diff can tell what changed.
#   (name, fill)
ANSWERS = [
    ("red", "stripe"),
    ("blue", "solid"),
    ("green", "dot"),
    ("yellow", "ring"),
    ("purple", "solid"),
    ("orange", "stripe"),
]

BASE_POOL = [0, 1, 2, 3]
BLITZ_POOL = [0, 1, 2, 3, 4, 5]
CVD_POOL = [0, 1, 2, 3]

# Difficulty, in declaration order: chill, classic, blitz.
#   (round_count, pool, incongruent_share)
PROFILES = [
    (20, BASE_POOL, 0.60),
    (30, BASE_POOL, 0.75),
    (40, BLITZ_POOL, 0.90),
]

DIFFICULTY_NAMES = ["chill", "classic", "blitz"]


def to_signed(value: int) -> int:
    """The two's-complement signed reading of a 64-bit pattern."""
    return value - (1 << 64) if value & SIGN_BIT else value


def fnv1a64(key: str) -> int:
    """FNV-1a over the UTF-8 BYTES of key, not its code units."""
    h = FNV_OFFSET
    for byte in key.encode("utf-8"):
        h = ((h ^ byte) * FNV_PRIME) & MASK64
    return h


class SplitMix64:
    """SplitMix64, transcribed from its published definition."""

    def __init__(self, seed: int) -> None:
        self.state = seed & MASK64

    def next_int64(self) -> int:
        self.state = (self.state + GOLDEN_GAMMA) & MASK64
        z = self.state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
        return z ^ (z >> 31)

    def next_int(self, bound: int) -> int:
        """Dart's `%` is Euclidean and so is Python's, which is what lets the
        two express the same definition without an abs() anywhere."""
        return to_signed(self.next_int64()) % bound


def seed_from(key: str, feature_salt: int, mode_salt: int) -> SplitMix64:
    mixed = fnv1a64(key) ^ ((feature_salt * GOLDEN_GAMMA) & MASK64) ^ mode_salt
    return SplitMix64(mixed & MASK64)


def draw_options(rng: SplitMix64, pool):
    """Four distinct answers whose FILLS are also distinct.

    Enumerating-and-filtering was considered and rejected: it would consume a
    different number of draws than the implementation does, so the two would
    diverge on every round after the first. What has to match is the DRAW
    SEQUENCE, so the shuffle is transcribed step for step and only the
    acceptance test is re-derived.
    """
    while True:
        shuffled = list(pool)
        for i in range(len(shuffled) - 1, 0, -1):
            j = rng.next_int(i + 1)
            shuffled[i], shuffled[j] = shuffled[j], shuffled[i]
        drawn = shuffled[:4]
        if len({ANSWERS[a][1] for a in drawn}) == 4:
            return drawn


def other_than(rng: SplitMix64, ink: int, pool) -> int:
    """Any answer in the POOL that is not the ink.

    From the pool rather than from every answer: the word may name a colour
    that is not among the four offered, but it must name one this run can
    paint. Drawing from the whole set let the colour-blind palette print a
    colour with no swapped hue.
    """
    others = [a for a in pool if a != ink]
    return others[rng.next_int(len(others))]


def generate(seed: int, difficulty: int, colour_blind: bool):
    round_count, pool, share = PROFILES[difficulty]
    rng = seed_from(f"stroop_rush:{seed}", STROOP_FEATURE_SALT, difficulty)
    pool = CVD_POOL if colour_blind else pool

    rounds = []
    for index in range(round_count):
        options = draw_options(rng, pool)
        ink = options[rng.next_int(len(options))]
        incongruent = rng.next_int(1000) < int(share * 1000)
        word = other_than(rng, ink, pool) if incongruent else ink
        rounds.append((index, word, ink, options, 1 if colour_blind else 0))
    return rounds


def canonical(r) -> str:
    index, word, ink, options, cvd = r
    return f"{index}:{word}:{ink}:{','.join(str(o) for o in options)}:{cvd}"


def fingerprint(rounds, take: int = 24) -> str:
    """FNV-1a-64 over the canonical rounds, as lowercase hex.

    Hex from int formatting, never a thousands-separated decimal: a fingerprint
    built by formatting is a fingerprint that can move with a locale.
    """
    joined = "|".join(canonical(r) for r in rounds[:take])
    return f"{fnv1a64(joined):016x}"


ROWS = [
    (0, 1, False, "seed 0 — the boundary a hash that forgot to mix collapses at"),
    (1, 1, False, "seed 1 — adjacent to 0, so a weak avalanche shows up as a near-identical row"),
    (424242, 1, False, "a mid-range seed, the one the other difficulties are compared at"),
    (0x7FFFFFFF, 1, False, "the largest 32-bit positive seed a caller might pass"),
    (-1, 1, False, "a negative seed: nextInt must stay non-negative through a Euclidean modulo"),
    (424242, 0, False, "chill at the mid-range seed — fewer rounds AND a different sequence"),
    (424242, 2, False, "blitz at the mid-range seed — six-answer pool, rejection sampling engaged"),
    (424242, 1, True, "classic, colour-blind: the pool is capped to four and the draws change"),
    (424242, 2, True, "blitz, colour-blind: the six-answer pool is capped, so no rejection occurs"),
    (99, 2, False, "a second blitz seed, so one rejection-sampled row is not the whole evidence"),
]


def main() -> None:
    lines = [
        "// GENERATED by tool/stroop_vectors_oracle.py. Do not edit by hand.",
        "//",
        "// Regenerate with:  python3 tool/stroop_vectors_oracle.py",
        "//",
        "// THIS TABLE WAS NOT PRODUCED BY THE CODE IT TESTS. The oracle is an",
        "// independent Python implementation of the PRNG, the seed derivation,",
        "// the shuffle and the four-draw order, written from the specification",
        "// in the generator's own doc comment, so it can disagree with",
        "// lib/games/stroop_rush/domain/stroop_round_generator.dart.",
        "//",
        "// It is LOCALE-FREE BY CONSTRUCTION: Python's int formatting has no",
        "// locale, so a fingerprint computed there cannot pick one up. That is",
        "// half the proof that the Dart side has not either — the other half is",
        "// the four-locale test that regenerates every row below.",
        "//",
        "// CI verifies these values; it never regenerates them.",
        "//",
        "// The library directive carries the header above; the lint reads only",
        "// the doc comment form and cannot see a `//` block.",
        "// ignore_for_file: unnecessary_library_directive",
        "library;",
        "",
        "import 'package:mindforge/core/difficulty.dart';",
        "",
        "/// One frozen row: what a (seed, difficulty, palette) triple deals.",
        "typedef StroopRoundVector = ({",
        "  int seed,",
        "  Difficulty difficulty,",
        "  bool isColourBlindPalette,",
        "  String fingerprint,",
        "  int incongruentCount,",
        "  String note,",
        "});",
        "",
        "/// The frozen table. A row that changes means a player's seed now deals",
        "/// a different game, which is never an accident worth accepting.",
        "const List<StroopRoundVector> stroopRoundVectors = <StroopRoundVector>[",
    ]

    for seed, difficulty, cvd, note in ROWS:
        rounds = generate(seed, difficulty, cvd)
        incongruent = sum(1 for r in rounds if r[1] != r[2])
        lines += [
            "  (",
            f"    seed: {seed},",
            f"    difficulty: Difficulty.{DIFFICULTY_NAMES[difficulty]},",
            f"    isColourBlindPalette: {'true' if cvd else 'false'},",
            f"    fingerprint: '{fingerprint(rounds)}',",
            f"    incongruentCount: {incongruent},",
            f"    note: '{note}',",
            "  ),",
        ]

    lines += ["];", ""]

    path = "test/games/stroop_rush/domain/stroop_vectors.dart"
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {path} — {len(ROWS)} rows")


if __name__ == "__main__":
    main()
