// Regenerates test/games/schulte_grid/domain/schulte_scramble_vectors.dart.
//
// CI NEVER RUNS THIS. A table the pipeline can rewrite is not frozen — it would
// re-bless whatever the code currently does, which is the one thing a golden
// vector exists to prevent. Run it by hand when the draw order changes on
// purpose, bump kSchulteGeneratorVersion in the same commit, and read the
// per-row diff it prints before committing the result.
// The fingerprint arithmetic below uses exact 64-bit integers, which are
// silently wrong on the web. This tool runs on a developer's machine and the
// app ships iOS only.
// ignore_for_file: avoid_js_rounded_ints
import 'dart:io';

import 'package:mindforge/games/schulte_grid/domain/schulte_scramble.dart';

/// The rows the table pins, and why each one is there.
const List<(int seed, int size, String note)> _rows =
    <(int seed, int size, String note)>[
      (0, 3, 'hand-computed anchor'),
      (1, 3, 'hand-computed anchor'),
      (2, 3, 'hand-computed anchor'),
      (3, 3, 'hand-computed anchor'),
      (0, 4, 'chill, the low seed'),
      (1, 4, 'chill, the next seed'),
      (0, 5, 'classic, the low seed'),
      (1, 5, 'classic, the next seed'),
      (2, 5, 'classic'),
      (42, 5, 'classic, the seed every test uses'),
      (999999, 5, 'classic, a large seed'),
      (0x7FFFFFFFFFFFFFFF, 5, 'classic, the largest positive seed'),
    ];

void main() {
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED by tool/update_schulte_vectors.dart. Do not edit'
      ' by hand.',
    )
    ..writeln('//')
    ..writeln(
      '// See the header on kSchulteScrambleVectors for what these'
      ' rows do and do',
    )
    ..writeln('// not prove.')
    ..writeln('//')
    ..writeln('// A fingerprint is an exact 64-bit integer on a native target')
    ..writeln('// and silently wrong on the web. The app ships iOS only, and')
    ..writeln('// the lint is suppressed here rather than repository-wide so')
    ..writeln('// it still fires anywhere else someone writes one — the same')
    ..writeln('// decision lib/core/seeded_generator.dart records.')
    ..writeln('// ignore_for_file: avoid_js_rounded_ints')
    ..writeln("import 'package:mindforge/core/seeded_generator.dart';")
    ..writeln()
    ..writeln('/// One frozen board.')
    ..writeln('typedef SchulteScrambleVector = ({')
    ..writeln('  int seed,')
    ..writeln('  int size,')
    ..writeln('  int fingerprint,')
    ..writeln('  int firstCell,')
    ..writeln('  int naturalPositions,')
    ..writeln('  String note,')
    ..writeln('});')
    ..writeln()
    ..writeln('/// The fingerprint of [cells].')
    ..writeln('///')
    ..writeln(
      "/// `join(',')` goes through `int.toString()`, which is ASCII by",
    )
    ..writeln(
      '/// definition and reads no ambient locale — so a fingerprint is',
    )
    ..writeln('/// locale-invariant BY CONSTRUCTION, not by luck. That is the')
    ..writeln(
      '/// line a well-meaning move to a NumberFormat would change, and',
    )
    ..writeln('/// schulte_scramble_locale_test is what would catch it.')
    ..writeln('int fingerprintOf(List<int> cells) =>')
    ..writeln("    fnv1a64(cells.join(','));")
    ..writeln()
    ..writeln('/// Boards frozen against accidental change.')
    ..writeln('///')
    ..writeln(
      '/// **Only the four size-3 rows are independently derived.** The',
    )
    ..writeln('/// rest are regression pins: they prove nothing changed, never')
    ..writeln(
      '/// that the output is right. What argues for correctness is the',
    )
    ..writeln('/// BigInt oracle in schulte_oracle.dart, which reimplements')
    ..writeln(
      '/// SplitMix64 and the shuffle from their definitions and agrees',
    )
    ..writeln('/// with production over 500 seeds at three sizes.')
    ..writeln('const List<SchulteScrambleVector> kSchulteScrambleVectors =')
    ..writeln('    <SchulteScrambleVector>[');

  for (final row in _rows) {
    final cells = schulteScramble(seed: row.$1, size: row.$2);

    buffer
      ..writeln('      (')
      ..writeln('        seed: ${row.$1},')
      ..writeln('        size: ${row.$2},')
      ..writeln('        fingerprint: ${_fingerprint(cells)},')
      ..writeln('        firstCell: ${cells.first},')
      ..writeln('        naturalPositions: ${naturalPositionCount(cells)},')
      ..writeln("        note: '${row.$3}',")
      ..writeln('      ),');
  }

  buffer.writeln('    ];');

  File(
    'test/games/schulte_grid/domain/schulte_scramble_vectors.dart',
  ).writeAsStringSync(buffer.toString());

  stdout.writeln('wrote ${_rows.length} vectors');
}

int _fingerprint(List<int> cells) {
  var hash = 0xCBF29CE484222325;

  for (final byte in cells.join(',').codeUnits) {
    hash = (hash ^ byte) * 0x100000001B3;
  }

  return hash;
}
