// Regenerates test/games/digit_bridge/domain/bridge_round_vectors.dart.
//
// CI NEVER RUNS THIS. A table the pipeline can rewrite is not frozen — it would
// re-bless whatever the code currently does, which is the one thing a golden
// vector exists to prevent. Run it by hand when the draw order changes on
// purpose, bump kBridgeGeneratorVersion in the same commit, and read the
// per-row diff it prints before committing the result.
import 'dart:io';

import 'package:mindforge/core/difficulty.dart';
import 'package:mindforge/core/seeded_generator.dart';
import 'package:mindforge/games/digit_bridge/domain/bridge_round_generator.dart';

/// The rows the table pins, and why each one is there.
const List<(int seed, Difficulty difficulty, String note)> _rows =
    <(int seed, Difficulty, String)>[
      (0, Difficulty.chill, 'chill, the low seed'),
      (1, Difficulty.chill, 'chill, the next seed'),
      (0, Difficulty.classic, 'classic, the low seed'),
      (1, Difficulty.classic, 'classic, the next seed'),
      (42, Difficulty.classic, 'classic, the seed every test uses'),
      (0, Difficulty.blitz, 'blitz, the low seed'),
      (999999, Difficulty.blitz, 'blitz, a large seed'),
      (
        0x7FFFFFFFFFFFFFFF,
        Difficulty.blitz,
        'blitz, the largest positive seed',
      ),
    ];

void main() {
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED by tool/update_bridge_vectors.dart. Do not edit by hand.',
    )
    ..writeln('//')
    ..writeln('// See the header on kBridgeRoundVectors for what these rows do')
    ..writeln('// and do not prove.')
    ..writeln('//')
    ..writeln('// A fingerprint is an exact 64-bit integer on a native target')
    ..writeln('// and silently wrong on the web. The app ships iOS only, and')
    ..writeln('// the lint is suppressed here rather than repository-wide so')
    ..writeln('// it still fires anywhere else someone writes one — the same')
    ..writeln('// decision lib/core/seeded_generator.dart records.')
    ..writeln('// ignore_for_file: avoid_js_rounded_ints')
    ..writeln("import 'package:mindforge/core/difficulty.dart';")
    ..writeln("import 'package:mindforge/core/seeded_generator.dart';")
    ..writeln(
      "import 'package:mindforge/games/digit_bridge/domain/bridge_round.dart';",
    )
    ..writeln()
    ..writeln('/// One frozen run.')
    ..writeln('typedef BridgeRoundVector = ({')
    ..writeln('  int seed,')
    ..writeln('  Difficulty difficulty,')
    ..writeln('  int fingerprint,')
    ..writeln('  int roundCount,')
    ..writeln('  int firstTarget,')
    ..writeln('  int firstCorrectIndex,')
    ..writeln('  String note,')
    ..writeln('});')
    ..writeln()
    ..writeln('/// The fingerprint of [rounds].')
    ..writeln('///')
    ..writeln('/// Built from `BridgeRound.canonical()`, which is integers and')
    ..writeln('/// enum indices joined by `int.toString()` — ASCII by')
    ..writeln('/// definition, reading no ambient locale. A fingerprint is')
    ..writeln('/// therefore locale-invariant BY CONSTRUCTION rather than by')
    ..writeln('/// luck, which for a game whose content IS numerals is the')
    ..writeln('/// property most worth holding on to.')
    ..writeln('int fingerprintOf(List<BridgeRound> rounds) =>')
    ..writeln("    fnv1a64(rounds.map((r) => r.canonical()).join('|'));")
    ..writeln()
    ..writeln('/// Runs frozen against accidental change.')
    ..writeln('///')
    ..writeln('/// **These are regression pins, not derivations.** They prove')
    ..writeln('/// nothing changed; they do not prove the output is right.')
    ..writeln('/// What argues for correctness is bridge_round_generator_test,')
    ..writeln('/// which checks the properties a Digit Bridge round has to')
    ..writeln('/// have — one winning chip, six distinct values, no leading')
    ..writeln('/// zero, a real adjacent swap behind every transposition — and')
    ..writeln('/// bridge_round_locale_test, which proves the table does not')
    ..writeln('/// move when the locale does.')
    ..writeln('///')
    ..writeln('/// There is deliberately no second-implementation oracle here.')
    ..writeln('/// The risky arithmetic is SplitMix64 and `%` on a negative')
    ..writeln('/// dividend, and that is already oracle-checked in')
    ..writeln(
      '/// test/core/seed_vectors.dart. A second copy of the distractor',
    )
    ..writeln('/// enumeration would be a transcription of this one, not an')
    ..writeln('/// independent derivation, and would argue for nothing.')
    ..writeln('const List<BridgeRoundVector> kBridgeRoundVectors =')
    ..writeln('    <BridgeRoundVector>[');

  for (final row in _rows) {
    final rounds = generateBridgeRounds(seed: row.$1, difficulty: row.$2);
    // THE SHIPPED HASH, not a copy of it. A tool that re-implemented FNV-1a
    // would compute the pinned value by a different code path from the test
    // that checks it, so a divergence in the copy would silently re-bless a
    // wrong table — which is the one thing a frozen vector exists to prevent.
    final fingerprint = fnv1a64(
      rounds.map((round) => round.canonical()).join('|'),
    );

    buffer
      ..writeln('      (')
      ..writeln('        seed: ${row.$1},')
      ..writeln('        difficulty: Difficulty.${row.$2.name},')
      ..writeln('        fingerprint: $fingerprint,')
      ..writeln('        roundCount: ${rounds.length},')
      ..writeln('        firstTarget: ${rounds.first.target},')
      ..writeln('        firstCorrectIndex: ${rounds.first.correctIndex},')
      ..writeln("        note: '${row.$3}',")
      ..writeln('      ),');
  }

  buffer.writeln('    ];');

  File(
    'test/games/digit_bridge/domain/bridge_round_vectors.dart',
  ).writeAsStringSync(buffer.toString());

  stdout.writeln('wrote ${_rows.length} vectors');
}
