// Regenerates test/games/false_light/domain/light_field_vectors.dart.
//
// CI NEVER RUNS THIS. A table the pipeline can rewrite is not frozen — it would
// re-bless whatever the code currently does, which is the one thing a golden
// vector exists to prevent. Run it by hand when the draw order changes on
// purpose, bump kFalseLightGeneratorVersion in the same commit, and read the
// per-row diff it prints before committing the result.
import 'dart:io';

import 'package:mindforge/core/difficulty.dart';
import 'package:mindforge/core/seeded_generator.dart';
import 'package:mindforge/games/false_light/domain/light_field_generator.dart';

/// The rows the table pins, and why each one is there.
const List<(int seed, Difficulty difficulty, String note)> _rows =
    <(int seed, Difficulty, String)>[
      (0, Difficulty.chill, 'chill, the low seed'),
      (1, Difficulty.chill, 'chill, the next seed'),
      (0, Difficulty.classic, 'classic, the low seed'),
      (1, Difficulty.classic, 'classic, the next seed'),
      (42, Difficulty.classic, 'classic, the seed every test uses'),
      (0, Difficulty.blitz, 'blitz, the low seed'),
      (999999, Difficulty.blitz, 'blitz, a large seed'),
      (
        0x7FFFFFFFFFFFFFFF,
        Difficulty.blitz,
        'blitz, the largest positive seed',
      ),
    ];

void main() {
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED by tool/update_light_vectors.dart. Do not edit by hand.',
    )
    ..writeln('//')
    ..writeln('// See the header on kLightFieldVectors for what these rows do')
    ..writeln('// and do not prove.')
    ..writeln('//')
    ..writeln('// A fingerprint is an exact 64-bit integer on a native target')
    ..writeln('// and silently wrong on the web. The app ships iOS only, and')
    ..writeln('// the lint is suppressed here rather than repository-wide so')
    ..writeln('// it still fires anywhere else someone writes one — the same')
    ..writeln('// decision lib/core/seeded_generator.dart records.')
    ..writeln('// ignore_for_file: avoid_js_rounded_ints')
    ..writeln("import 'package:mindforge/core/difficulty.dart';")
    ..writeln("import 'package:mindforge/core/seeded_generator.dart';")
    ..writeln(
      "import 'package:mindforge/games/false_light/domain/light_field.dart';",
    )
    ..writeln()
    ..writeln('/// One frozen run.')
    ..writeln('typedef LightFieldVector = ({')
    ..writeln('  int seed,')
    ..writeln('  Difficulty difficulty,')
    ..writeln('  int fingerprint,')
    ..writeln('  int fieldCount,')
    ..writeln('  int firstPressedCount,')
    ..writeln('  int totalPressed,')
    ..writeln('  String note,')
    ..writeln('});')
    ..writeln()
    ..writeln('/// The fingerprint of [fields].')
    ..writeln('///')
    ..writeln('/// Built from `LightField.canonical()`, which is integers and')
    ..writeln('/// enum indices joined by `int.toString()` — ASCII by')
    ..writeln('/// definition, reading no ambient locale. A fingerprint is')
    ..writeln('/// therefore locale-invariant BY CONSTRUCTION rather than by')
    ..writeln('/// luck. For a board that renders no text at all this is the')
    ..writeln('/// easiest property in the app to hold and the easiest to lose')
    ..writeln('/// silently, since nothing on screen would look wrong.')
    ..writeln('int fingerprintOf(List<LightField> fields) =>')
    ..writeln("    fnv1a64(fields.map((f) => f.canonical()).join('|'));")
    ..writeln()
    ..writeln('/// Runs frozen against accidental change.')
    ..writeln('///')
    ..writeln('/// **These are regression pins, not derivations.** They prove')
    ..writeln('/// nothing changed; they do not prove the output is right.')
    ..writeln('/// What argues for correctness is light_field_generator_test,')
    ..writeln('/// which checks the properties a False Light field has to')
    ..writeln('/// have — every field playable, at least one pressed and at')
    ..writeln('/// least one raised tile, the count inside the profile band,')
    ..writeln('/// the positions spread over the whole grid — and')
    ..writeln('/// light_field_locale_test, which proves the table does not')
    ..writeln('/// move when the locale does.')
    ..writeln('///')
    ..writeln('/// There is deliberately no second-implementation oracle here.')
    ..writeln('/// The risky arithmetic is SplitMix64 and `%` on a negative')
    ..writeln('/// dividend, and that is already oracle-checked in')
    ..writeln('/// test/core/seed_vectors.dart. A second copy of the partial')
    ..writeln('/// Fisher-Yates would be a transcription of this one, not an')
    ..writeln('/// independent derivation, and would argue for nothing.')
    ..writeln('const List<LightFieldVector> kLightFieldVectors =')
    ..writeln('    <LightFieldVector>[');

  for (final row in _rows) {
    final fields = generateLightFields(seed: row.$1, difficulty: row.$2);
    // THE SHIPPED HASH, not a copy of it. A tool that re-implemented FNV-1a
    // would compute the pinned value by a different code path from the test
    // that checks it, so a divergence in the copy would silently re-bless a
    // wrong table — which is the one thing a frozen vector exists to prevent.
    final fingerprint = fnv1a64(
      fields.map((field) => field.canonical()).join('|'),
    );
    final totalPressed = fields.fold<int>(
      0,
      (sum, field) => sum + field.pressedCount,
    );

    buffer
      ..writeln('      (')
      ..writeln('        seed: ${row.$1},')
      ..writeln('        difficulty: Difficulty.${row.$2.name},')
      ..writeln('        fingerprint: $fingerprint,')
      ..writeln('        fieldCount: ${fields.length},')
      ..writeln('        firstPressedCount: ${fields.first.pressedCount},')
      ..writeln('        totalPressed: $totalPressed,')
      ..writeln("        note: '${row.$3}',")
      ..writeln('      ),');
  }

  buffer.writeln('    ];');

  File(
    'test/games/false_light/domain/light_field_vectors.dart',
  ).writeAsStringSync(buffer.toString());

  stdout.writeln('wrote ${_rows.length} vectors');
}
