// GENERATED by tool/update_bridge_vectors.dart. Do not edit by hand.
//
// See the header on kBridgeRoundVectors for what these rows do
// and do not prove.
//
// A fingerprint is an exact 64-bit integer on a native target
// and silently wrong on the web. The app ships iOS only, and
// the lint is suppressed here rather than repository-wide so
// it still fires anywhere else someone writes one — the same
// decision lib/core/seeded_generator.dart records.
// ignore_for_file: avoid_js_rounded_ints
import 'package:mindforge/core/difficulty.dart';
import 'package:mindforge/core/seeded_generator.dart';
import 'package:mindforge/games/digit_bridge/domain/bridge_round.dart';

/// One frozen run.
typedef BridgeRoundVector = ({
  int seed,
  Difficulty difficulty,
  int fingerprint,
  int roundCount,
  int firstTarget,
  int firstCorrectIndex,
  String note,
});

/// The fingerprint of [rounds].
///
/// Built from `BridgeRound.canonical()`, which is integers and
/// enum indices joined by `int.toString()` — ASCII by
/// definition, reading no ambient locale. A fingerprint is
/// therefore locale-invariant BY CONSTRUCTION rather than by
/// luck, which for a game whose content IS numerals is the
/// property most worth holding on to.
int fingerprintOf(List<BridgeRound> rounds) =>
    fnv1a64(rounds.map((r) => r.canonical()).join('|'));

/// Runs frozen against accidental change.
///
/// **These are regression pins, not derivations.** They prove
/// nothing changed; they do not prove the output is right.
/// What argues for correctness is bridge_round_generator_test,
/// which checks the properties a Digit Bridge round has to
/// have — one winning chip, six distinct values, no leading
/// zero, a real adjacent swap behind every transposition — and
/// bridge_round_locale_test, which proves the table does not
/// move when the locale does.
///
/// There is deliberately no second-implementation oracle here.
/// The risky arithmetic is SplitMix64 and `%` on a negative
/// dividend, and that is already oracle-checked in
/// test/core/seed_vectors.dart. A second copy of the distractor
/// enumeration would be a transcription of this one, not an
/// independent derivation, and would argue for nothing.
const List<BridgeRoundVector> kBridgeRoundVectors = <BridgeRoundVector>[
  (
    seed: 0,
    difficulty: Difficulty.chill,
    fingerprint: 7766287233670779038,
    roundCount: 12,
    firstTarget: 723,
    firstCorrectIndex: 1,
    note: 'chill, the low seed',
  ),
  (
    seed: 1,
    difficulty: Difficulty.chill,
    fingerprint: 5912753612498952056,
    roundCount: 12,
    firstTarget: 417,
    firstCorrectIndex: 1,
    note: 'chill, the next seed',
  ),
  (
    seed: 0,
    difficulty: Difficulty.classic,
    fingerprint: -5363974802657606367,
    roundCount: 18,
    firstTarget: 4216,
    firstCorrectIndex: 1,
    note: 'classic, the low seed',
  ),
  (
    seed: 1,
    difficulty: Difficulty.classic,
    fingerprint: 3062422426599515096,
    roundCount: 18,
    firstTarget: 4629,
    firstCorrectIndex: 3,
    note: 'classic, the next seed',
  ),
  (
    seed: 42,
    difficulty: Difficulty.classic,
    fingerprint: 1979011975759578251,
    roundCount: 18,
    firstTarget: 3577,
    firstCorrectIndex: 1,
    note: 'classic, the seed every test uses',
  ),
  (
    seed: 0,
    difficulty: Difficulty.blitz,
    fingerprint: 95345172202915443,
    roundCount: 24,
    firstTarget: 30024,
    firstCorrectIndex: 1,
    note: 'blitz, the low seed',
  ),
  (
    seed: 999999,
    difficulty: Difficulty.blitz,
    fingerprint: -8595560223354897209,
    roundCount: 24,
    firstTarget: 57847,
    firstCorrectIndex: 3,
    note: 'blitz, a large seed',
  ),
  (
    seed: 9223372036854775807,
    difficulty: Difficulty.blitz,
    fingerprint: -4811725321736724785,
    roundCount: 24,
    firstTarget: 68231,
    firstCorrectIndex: 0,
    note: 'blitz, the largest positive seed',
  ),
];
