import 'package:flutter_test/flutter_test.dart';
import 'package:intl/intl.dart';
import 'package:mindforge/core/seeded_generator.dart';
import 'package:mindforge/games/stroop_rush/domain/stroop_round.dart';
import 'package:mindforge/games/stroop_rush/domain/stroop_round_generator.dart';

import '../../../support/locale_matrix.dart';
import 'stroop_vectors.dart';

/// What each `(seed, difficulty, palette)` triple means, frozen.
///
/// A shipped generator is frozen: a player's seed has to deal the same game
/// tomorrow, on a different device, on a future SDK — otherwise "the Blitz
/// round gave me two orange keys" is a story rather than a bug report.
///
/// The table was produced by `tool/stroop_vectors_oracle.py`, which is not this
/// code. A table generated by the implementation freezes that implementation's
/// bugs as the specification.
void main() {
  /// FNV-1a-64 over the canonical rounds, as lowercase hex.
  ///
  /// **`toRadixString(16)`, never `'$value'` and never `NumberFormat`.** A
  /// fingerprint built by formatting is a fingerprint that moves with the
  /// ambient locale: under `Intl.defaultLocale = 'fa'` a formatted integer
  /// emits Eastern Arabic digits, and the hash changes for a reason that has
  /// nothing to do with the game. The locale sweep below is what proves this
  /// helper is hashing rather than formatting.
  String fingerprintOf(List<StroopRound> rounds, {int take = 24}) {
    final joined = rounds
        .take(take)
        .map((round) => round.canonical())
        .join('|');

    return _hex64(fnv1a64(joined));
  }

  List<StroopRound> roundsFor(StroopRoundVector vector) => generateStroopRounds(
    seed: vector.seed,
    difficulty: vector.difficulty,
    isColourBlindPalette: vector.isColourBlindPalette,
  );

  group('the frozen table', () {
    test('has ten rows, each explaining why it exists', () {
      expect(stroopRoundVectors, hasLength(10));

      for (final vector in stroopRoundVectors) {
        expect(vector.note, isNotEmpty);
      }
    });

    test('and no duplicate fingerprints, which would be a copy-pasted row', () {
      expect(
        stroopRoundVectors.map((vector) => vector.fingerprint).toSet(),
        hasLength(stroopRoundVectors.length),
      );
    });
  });

  group('the generator reproduces every frozen vector', () {
    for (final vector in stroopRoundVectors) {
      test(
        'seed ${vector.seed} ${vector.difficulty.name}'
        '${vector.isColourBlindPalette ? ' cvd' : ''}',
        () {
          final rounds = roundsFor(vector);

          expect(
            fingerprintOf(rounds),
            vector.fingerprint,
            reason: vector.note,
          );
          expect(
            rounds.where((round) => !round.isCongruent).length,
            vector.incongruentCount,
            reason: vector.note,
          );
        },
      );
    }
  });

  group('the vectors are identical in every locale', () {
    // THE PROOF THAT LOCALISATION CANNOT REACH GENERATION. Two failure modes
    // it catches, both one careless commit away: a `PlayAnswer.name` that got
    // localized, and a fingerprint built by interpolating an int under an
    // ambient `Intl.defaultLocale = 'fa'`, which emits ۱۲ and changes the hash.
    //
    // It is not multiplied out into forty named tests on purpose: what is
    // being asserted is that the locale is IRRELEVANT, and a per-locale test
    // name suggests it is a variable.
    for (final tag in localeMatrix) {
      test('under $tag, every row still matches', () {
        final previous = Intl.defaultLocale;

        addTearDown(() => Intl.defaultLocale = previous);
        Intl.defaultLocale = tag;

        for (final vector in stroopRoundVectors) {
          expect(
            fingerprintOf(roundsFor(vector)),
            vector.fingerprint,
            reason: 'seed ${vector.seed} under $tag: ${vector.note}',
          );
        }
      });
    }

    test('and the canonical form itself is ASCII under fa', () {
      // The narrower statement, so a failure says WHICH half broke. If the
      // canonical string picks up Eastern Arabic digits then the round is
      // formatting; if it stays ASCII and the fingerprint still moved, the
      // helper is.
      final previous = Intl.defaultLocale;

      addTearDown(() => Intl.defaultLocale = previous);
      Intl.defaultLocale = 'fa';

      for (final round in roundsFor(stroopRoundVectors.first)) {
        expect(round.canonical(), matches(RegExp(r'^[0-9:,]+$')));
      }
    });
  });
}

/// A 64-bit value as sixteen lowercase hex digits.
///
/// Split into two 32-bit halves with a LOGICAL shift, because Dart's `int` is
/// signed and `toRadixString(16)` on a negative one emits `-1f3a…` — a
/// seventeen-character string that is not a two's-complement reading of
/// anything. The oracle prints `f"{value:016x}"` over an unsigned Python int,
/// and this is the same sixteen digits.
///
/// It is also the reason this helper exists at all rather than an interpolation:
/// `toRadixString` takes no locale and cannot acquire one.
String _hex64(int value) {
  final high = (value >>> 32) & 0xFFFFFFFF;
  final low = value & 0xFFFFFFFF;

  return high.toRadixString(16).padLeft(8, '0') +
      low.toRadixString(16).padLeft(8, '0');
}
