// GENERATED by tool/stroop_vectors_oracle.py. Do not edit by hand.
//
// Regenerate with:  python3 tool/stroop_vectors_oracle.py
//
// THIS TABLE WAS NOT PRODUCED BY THE CODE IT TESTS. The oracle is an
// independent Python implementation of the PRNG, the seed derivation,
// the shuffle and the four-draw order, written from the specification
// in the generator's own doc comment, so it can disagree with
// lib/games/stroop_rush/domain/stroop_round_generator.dart.
//
// It is LOCALE-FREE BY CONSTRUCTION: Python's int formatting has no
// locale, so a fingerprint computed there cannot pick one up. That is
// half the proof that the Dart side has not either — the other half is
// the four-locale test that regenerates every row below.
//
// CI verifies these values; it never regenerates them.
//
// The library directive carries the header above; the lint reads only
// the doc comment form and cannot see a `//` block.
// ignore_for_file: unnecessary_library_directive
library;

import 'package:mindforge/core/difficulty.dart';

/// One frozen row: what a (seed, difficulty, palette) triple deals.
typedef StroopRoundVector = ({
  int seed,
  Difficulty difficulty,
  bool isColourBlindPalette,
  String fingerprint,
  int incongruentCount,
  String note,
});

/// The frozen table. A row that changes means a player's seed now deals
/// a different game, which is never an accident worth accepting.
const List<StroopRoundVector> stroopRoundVectors = <StroopRoundVector>[
  (
    seed: 0,
    difficulty: Difficulty.classic,
    isColourBlindPalette: false,
    fingerprint: '3d6224d7d38a1e25',
    incongruentCount: 20,
    note: 'seed 0 — the boundary a hash that forgot to mix collapses at',
  ),
  (
    seed: 1,
    difficulty: Difficulty.classic,
    isColourBlindPalette: false,
    fingerprint: '2f190adc398ccd75',
    incongruentCount: 22,
    note:
        'seed 1 — adjacent to 0, so a weak avalanche shows up as a near-identical row',
  ),
  (
    seed: 424242,
    difficulty: Difficulty.classic,
    isColourBlindPalette: false,
    fingerprint: '9aff397c0af5eb4e',
    incongruentCount: 23,
    note: 'a mid-range seed, the one the other difficulties are compared at',
  ),
  (
    seed: 2147483647,
    difficulty: Difficulty.classic,
    isColourBlindPalette: false,
    fingerprint: 'f2f0433e8d74b02f',
    incongruentCount: 22,
    note: 'the largest 32-bit positive seed a caller might pass',
  ),
  (
    seed: -1,
    difficulty: Difficulty.classic,
    isColourBlindPalette: false,
    fingerprint: 'a6d15ea682492eef',
    incongruentCount: 18,
    note:
        'a negative seed: nextInt must stay non-negative through a Euclidean modulo',
  ),
  (
    seed: 424242,
    difficulty: Difficulty.chill,
    isColourBlindPalette: false,
    fingerprint: '9f25120b13cedddf',
    incongruentCount: 7,
    note: 'chill at the mid-range seed — fewer rounds AND a different sequence',
  ),
  (
    seed: 424242,
    difficulty: Difficulty.blitz,
    isColourBlindPalette: false,
    fingerprint: '8bc95fa0eae75a38',
    incongruentCount: 39,
    note:
        'blitz at the mid-range seed — six-answer pool, rejection sampling engaged',
  ),
  (
    seed: 424242,
    difficulty: Difficulty.classic,
    isColourBlindPalette: true,
    fingerprint: '08f4aebfa6350f30',
    incongruentCount: 23,
    note:
        'classic, colour-blind: the pool is capped to four and the draws change',
  ),
  (
    seed: 424242,
    difficulty: Difficulty.blitz,
    isColourBlindPalette: true,
    fingerprint: 'd8b4122424b1de6f',
    incongruentCount: 37,
    note:
        'blitz, colour-blind: the six-answer pool is capped, so no rejection occurs',
  ),
  (
    seed: 99,
    difficulty: Difficulty.blitz,
    isColourBlindPalette: false,
    fingerprint: '1955117b5609a6c2',
    incongruentCount: 36,
    note:
        'a second blitz seed, so one rejection-sampled row is not the whole evidence',
  ),
];
