// GENERATED by tool/update_light_vectors.dart. Do not edit by hand.
//
// See the header on kLightFieldVectors for what these rows do
// and do not prove.
//
// A fingerprint is an exact 64-bit integer on a native target
// and silently wrong on the web. The app ships iOS only, and
// the lint is suppressed here rather than repository-wide so
// it still fires anywhere else someone writes one — the same
// decision lib/core/seeded_generator.dart records.
// ignore_for_file: avoid_js_rounded_ints
import 'package:mindforge/core/difficulty.dart';
import 'package:mindforge/core/seeded_generator.dart';
import 'package:mindforge/games/false_light/domain/light_field.dart';

/// One frozen run.
typedef LightFieldVector = ({
  int seed,
  Difficulty difficulty,
  int fingerprint,
  int fieldCount,
  int firstPressedCount,
  int totalPressed,
  String note,
});

/// The fingerprint of [fields].
///
/// Built from `LightField.canonical()`, which is integers and
/// enum indices joined by `int.toString()` — ASCII by
/// definition, reading no ambient locale. A fingerprint is
/// therefore locale-invariant BY CONSTRUCTION rather than by
/// luck. For a board that renders no text at all this is the
/// easiest property in the app to hold and the easiest to lose
/// silently, since nothing on screen would look wrong.
int fingerprintOf(List<LightField> fields) =>
    fnv1a64(fields.map((f) => f.canonical()).join('|'));

/// Runs frozen against accidental change.
///
/// **These are regression pins, not derivations.** They prove
/// nothing changed; they do not prove the output is right.
/// What argues for correctness is light_field_generator_test,
/// which checks the properties a False Light field has to
/// have — every field playable, at least one pressed and at
/// least one raised tile, the count inside the profile band,
/// the positions spread over the whole grid — and
/// light_field_locale_test, which proves the table does not
/// move when the locale does.
///
/// There is deliberately no second-implementation oracle here.
/// The risky arithmetic is SplitMix64 and `%` on a negative
/// dividend, and that is already oracle-checked in
/// test/core/seed_vectors.dart. A second copy of the partial
/// Fisher-Yates would be a transcription of this one, not an
/// independent derivation, and would argue for nothing.
const List<LightFieldVector> kLightFieldVectors = <LightFieldVector>[
  (
    seed: 0,
    difficulty: Difficulty.chill,
    fingerprint: 6514856595675798044,
    fieldCount: 8,
    firstPressedCount: 6,
    totalPressed: 47,
    note: 'chill, the low seed',
  ),
  (
    seed: 1,
    difficulty: Difficulty.chill,
    fingerprint: 7531514915815130896,
    fieldCount: 8,
    firstPressedCount: 5,
    totalPressed: 45,
    note: 'chill, the next seed',
  ),
  (
    seed: 0,
    difficulty: Difficulty.classic,
    fingerprint: 324867276829543025,
    fieldCount: 12,
    firstPressedCount: 6,
    totalPressed: 70,
    note: 'classic, the low seed',
  ),
  (
    seed: 1,
    difficulty: Difficulty.classic,
    fingerprint: -4938227577676997932,
    fieldCount: 12,
    firstPressedCount: 7,
    totalPressed: 73,
    note: 'classic, the next seed',
  ),
  (
    seed: 42,
    difficulty: Difficulty.classic,
    fingerprint: -6919467593344912859,
    fieldCount: 12,
    firstPressedCount: 6,
    totalPressed: 70,
    note: 'classic, the seed every test uses',
  ),
  (
    seed: 0,
    difficulty: Difficulty.blitz,
    fingerprint: -9001913485110672420,
    fieldCount: 16,
    firstPressedCount: 8,
    totalPressed: 121,
    note: 'blitz, the low seed',
  ),
  (
    seed: 999999,
    difficulty: Difficulty.blitz,
    fingerprint: -5743515852204618807,
    fieldCount: 16,
    firstPressedCount: 7,
    totalPressed: 116,
    note: 'blitz, a large seed',
  ),
  (
    seed: 9223372036854775807,
    difficulty: Difficulty.blitz,
    fingerprint: 3280418844945937844,
    fieldCount: 16,
    firstPressedCount: 6,
    totalPressed: 111,
    note: 'blitz, the largest positive seed',
  ),
];
